In [1]:
import pandas as pd
import numpy as np
import datetime as datetime
import time

In [11]:
df = pd.read_csv('76fda9d0-69be-4dd5-8108-0de7907fc5a4.csv')

In [12]:
df.head(3), df.tail(3)

(   REQUEST_ID           CREATED_ON                    REQUEST_TYPE  \
 0      168714  2017-07-10T14:32:00  Fire Safety System Not Working
 1      251339  2018-05-22T12:12:00                 Illegal Dumping
 2      168709  2017-07-10T14:29:00                        Potholes

   REQUEST_ORIGIN  STATUS                         DEPARTMENT NEIGHBORHOOD  \
 0  Control Panel       1  Permits, Licenses and Inspections      Carrick
 1        Website       1                     DOMI - Permits     Garfield
 2    Call Center       1           DPW - Street Maintenance  Polish Hill

    COUNCIL_DISTRICT  WARD         TRACT  PUBLIC_WORKS_DIVISION  PLI_DIVISION  \
 0               4.0  29.0  4.200329e+10                    3.0          29.0
 1               9.0  10.0  4.200310e+10                    2.0          10.0
 2               7.0   6.0  4.200306e+10                    6.0           6.0

    POLICE_ZONE FIRE_ZONE          X          Y GEO_ACCURACY
 0          3.0      4-15 -79.980279  40.388412  APPROXIMATE
 1          5.0       3-4 -79.938336  40.466358  APPROXIMATE
 2          2.0       2-6 -79.965908  40.457074        EXACT  ,
         REQUEST_ID           CREATED_ON          REQUEST_TYPE REQUEST_ORIGIN  \
 284696      298013  2018-10-29T15:10:00        Rodent control    Call Center
 284697      298015  2018-10-29T15:13:00              Sinkhole    Call Center
 284698      298016  2018-10-29T15:15:00  Catch Basin, Clogged    Call Center

         STATUS                            DEPARTMENT  \
 284696       0                 Animal Care & Control
 284697       0              DPW - Street Maintenance
 284698       0  Pittsburgh Water and Sewer Authority

                      NEIGHBORHOOD  COUNCIL_DISTRICT  WARD         TRACT  \
 284696                  Beechview               4.0  19.0  4.200319e+10
 284697  Central Business District               6.0   2.0  4.200302e+10
 284698            Central Oakland               3.0   4.0  4.200304e+10

         PUBLIC_WORKS_DIVISION  PLI_DIVISION  POLICE_ZONE FIRE_ZONE          X  \
 284696                    5.0          19.0          6.0      4-28 -80.029806
 284697                    6.0           2.0          2.0       1-3 -79.998029
 284698                    3.0           4.0          4.0      2-11 -79.955304

                 Y GEO_ACCURACY
 284696  40.401053  APPROXIMATE
 284697  40.443594        EXACT
 284698  40.436586        EXACT  )

In [13]:
df.describe()

,REQUEST_ID,STATUS,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,X,Y
count,284699.000000,284699.000000,262942.000000,262637.000000,2.637620e+05,262644.000000,262637.000000,262469.000000,266079.000000,266079.000000
mean,151577.244567,1.189836,4.851945,16.351150,4.200323e+10,3.071637,16.351150,3.582084,-79.285273,40.092352
std,85402.774225,0.712178,2.533971,8.042901,1.896462e+05,1.454669,8.042901,1.593415,7.385783,3.734819
min,538.000000,0.000000,1.000000,0.000000,4.200301e+10,0.000000,0.000000,1.000000,-87.621300,0.000000
25%,79937.500000,1.000000,3.000000,10.000000,4.200311e+10,2.000000,10.000000,2.000000,-80.007370,40.421068
50%,153171.000000,1.000000,5.000000,16.000000,4.200318e+10,3.000000,16.000000,4.000000,-79.976979,40.443494
75%,225148.500000,1.000000,7.000000,21.000000,4.200329e+10,5.000000,21.000000,5.000000,-79.935019,40.461501
max,298016.000000,3.000000,9.000000,32.000000,4.200398e+10,6.000000,32.000000,6.000000,0.000000,41.885800

In [15]:
df = df[df['CREATED_ON'].str.contains('2017-')]
df = df.sort_values(ascending=False, axis=0, by=['REQUEST_ID'])
df.reset_index(drop=True, inplace=True)
df.describe()

,REQUEST_ID,STATUS,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,X,Y
count,79852.000000,79852.000000,76069.000000,75965.000000,7.612800e+04,75966.000000,75965.000000,75922.000000,76784.000000,76784.000000
mean,164666.873704,1.176514,4.882370,16.369157,4.200323e+10,3.029619,16.369157,3.550815,-79.289558,40.095406
std,23625.934393,0.703213,2.571621,8.025851,1.887250e+05,1.461813,8.025851,1.607305,7.360487,3.722107
min,123268.000000,0.000000,1.000000,0.000000,4.200301e+10,0.000000,0.000000,1.000000,-80.088105,0.000000
25%,144463.750000,1.000000,3.000000,10.000000,4.200311e+10,2.000000,10.000000,2.000000,-80.007287,40.421424
50%,164863.500000,1.000000,5.000000,16.000000,4.200318e+10,3.000000,16.000000,4.000000,-79.977465,40.444844
75%,185093.250000,1.000000,7.000000,22.000000,4.200328e+10,5.000000,22.000000,5.000000,-79.934367,40.461995
max,205290.000000,3.000000,9.000000,32.000000,4.200398e+10,6.000000,32.000000,6.000000,0.000000,40.526962

In [16]:
df.head()

,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,STATUS,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
0,205290,2017-12-31T23:17:00,Snow/Ice removal,Website,1,DPW - Street Maintenance,Marshall-Shadeland,1.0,27.0,4.200327e+10,1.0,27.0,1.0,1-14,-80.034743,40.472660,EXACT
1,205289,2017-12-31T22:01:00,Snow/Ice removal,Report2Gov iOS,1,DPW - Street Maintenance,Stanton Heights,9.0,10.0,4.200310e+10,2.0,10.0,5.0,3-7,-79.936661,40.480244,EXACT
2,205288,2017-12-31T21:55:00,Snow/Ice removal,Website,1,DPW - Street Maintenance,New Homestead,5.0,31.0,4.200331e+10,3.0,31.0,4.0,4-20,-79.927033,40.389385,EXACT
3,205287,2017-12-31T18:23:00,Missed Pick Up,Website,1,DPW - Refuse,Mount Washington,2.0,19.0,4.200319e+10,5.0,19.0,3.0,4-27,-80.014213,40.426213,APPROXIMATE
4,205286,2017-12-31T17:56:00,Snow/Ice removal,Report2Gov iOS,1,DPW - Street Maintenance,Stanton Heights,9.0,10.0,4.200310e+10,2.0,10.0,5.0,3-7,-79.937035,40.480705,EXACT

In [17]:
df.tail()

,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,STATUS,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
79847,123272,2017-01-01T16:21:00,Illegal Parking,Website,1,Police - Zones 1-6,Manchester,6.0,21.0,4.200321e+10,1.0,21.0,1.0,1-8,-80.023669,40.453135,APPROXIMATE
79848,123271,2017-01-01T12:57:00,Performance,Website,1,OMI,Central Business District,6.0,2.0,4.200302e+10,6.0,2.0,2.0,1-4,-79.995948,40.439508,APPROXIMATE
79849,123270,2017-01-01T12:07:00,Excessive Noise/Disturbances,Website,3,Police - Zones 1-6,South Side Flats,3.0,17.0,4.200317e+10,3.0,17.0,3.0,4-24,-79.985020,40.427285,APPROXIMATE
79850,123269,2017-01-01T12:06:00,Excessive Noise/Disturbances,Website,3,Police - Zones 1-6,South Side Flats,3.0,17.0,4.200317e+10,3.0,17.0,3.0,4-24,-79.984970,40.427448,APPROXIMATE
79851,123268,2017-01-01T08:11:00,Retaining Wall,Website,3,DPW - Construction Division,Central Business District,6.0,1.0,4.200302e+10,6.0,1.0,2.0,1-4,-79.998756,40.436495,EXACT

In [10]:
df.head()

,index,REQUEST_ID,CREATED_ON,REQUEST_TYPE,REQUEST_ORIGIN,STATUS,DEPARTMENT,NEIGHBORHOOD,COUNCIL_DISTRICT,WARD,TRACT,PUBLIC_WORKS_DIVISION,PLI_DIVISION,POLICE_ZONE,FIRE_ZONE,X,Y,GEO_ACCURACY
0,263815,205290,2017-12-31T23:17:00,Snow/Ice removal,Website,1,DPW - Street Maintenance,Marshall-Shadeland,1.0,27.0,4.200327e+10,1.0,27.0,1.0,1-14,-80.034743,40.472660,EXACT
1,251479,205289,2017-12-31T22:01:00,Snow/Ice removal,Report2Gov iOS,1,DPW - Street Maintenance,Stanton Heights,9.0,10.0,4.200310e+10,2.0,10.0,5.0,3-7,-79.936661,40.480244,EXACT
2,191536,205288,2017-12-31T21:55:00,Snow/Ice removal,Website,1,DPW - Street Maintenance,New Homestead,5.0,31.0,4.200331e+10,3.0,31.0,4.0,4-20,-79.927033,40.389385,EXACT
3,246027,205287,2017-12-31T18:23:00,Missed Pick Up,Website,1,DPW - Refuse,Mount Washington,2.0,19.0,4.200319e+10,5.0,19.0,3.0,4-27,-80.014213,40.426213,APPROXIMATE
4,245860,205286,2017-12-31T17:56:00,Snow/Ice removal,Report2Gov iOS,1,DPW - Street Maintenance,Stanton Heights,9.0,10.0,4.200310e+10,2.0,10.0,5.0,3-7,-79.937035,40.480705,EXACT

In [18]:
#should be ~14MB cleaned to 2017
with open('311cleaned.csv', 'w') as fh:
    df.to_csv(fh, index=False)